### PR TITLE
Adding PACMod 3 compatibility to the newly reorganized game control node 

### PR DESCRIPTION
**Pull request by KyleARectorAStuff**
Also includes mechanism for extending compatibility to future boards

### CODE REVIEW

**Comment by lbucklandAS** [comment]
I like it!

**Comment by KyleARectorAStuff** [comment]
@JWhitleyAStuff The second change is already in progress. I will look into the first.

**Comment by KyleARectorAStuff** [comment]
@lbucklandAS I made some changes after your approval, per @JWhitleyAStuff's recommendation. Please take a look if you have the opportunity. 

Thanks!

**Comment by lbucklandAS** [comment]
@KyleARectorAStuff Changes look good.

**Comment by joekale** [comment]
Small change request. The ROS_ERROR message should only tell the user what they need to know. The catch statement knows why it received an invalid_argument exception. Suggest changing to "Invalid PACMod Board Version received. Board requested was <board_rev>".

**Comment by JWhitleyAStuff** [comment]
@KyleARector - See my comment in the launch file changes. Here is the detail:
https://github.com/ros/ros_comm/pull/762

**Comment by JWhitleyAStuff** [comment]
Looks awesome. All good as far as I'm concerned. Once Travis finishes his thing, I'll merge.

**Pull request merged**
