### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by lbucklandAS**
The functionality remains the same, but the code is reorganized to make it easier to add new boards and modify existing code.

### CODE REVIEW

**Comment by lbucklandAS** [comment]
This has been tested and works fully on a GEM 4.

**Comment by JWhitleyAStuff** [comment]
@lbucklandAS - Would you mind squashing as many of these as you're comfortable with so it's easier to review?

**Comment by lbucklandAS** [comment]
@JWhitleyAStuff I am not sure what you are looking for here, do you mind clarifying? Just give me a call when you're free.

**Comment by JWhitleyAStuff** [comment]
Nevermind. I'm an idiot. I'll look it over tomorrow.

**Comment by lbucklandAS** [comment]
@samrustan Good call on these. The lines 56-60 have "vehicle_2" and "vehicle_4" because those are yet to be formally defined, but we wanted numbers for those. The jury is out I guess on what we want to do there. 
The lines 72-77 need those macros added you're right, I will fix that. Also the "fix this" todo is actually already fixed but I forgot to take that out, so I will do that thanks.

**Comment by lbucklandAS** [comment]
@samrustan Yeah they will be squashed unfortunately. We will have to manually re-add, though I think it's only a couple lines?

**Comment by lbucklandAS** [comment]
@samrustan Talked to @lyletbjohnson about this and we came to the conclusion that it's better to make those changes as part of the PR because of the unique circumstances. So I'll do that now and get the changes up, possibly after rescinding the PR. Thanks for pointing this out!

**Pull request closed without merging**
